### PR TITLE
Prop enum and *Query refactor

### PR DESCRIPTION
**Pull request by DavidFair**
### Description:
- Unify `from_string` into a single place in prop_enum
- Simplify init and add tests to *Query Objects

Another PR will extract `QueryWrapper` out to a factory, but I want to keep these small

### Special Notes:

---

### Submitter:

Have you (where applicable):

* [x] Added unit tests?
* [ ] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

### CODE REVIEW

File: lib/openstack_query/queries/server_query.py [hunk 1]
```diff
@@ -22,17 +24,20 @@
...
 
-    prop_enum_cls = ServerProperties
-    runner_cls = ServerRunner
+    @property
+    def prop_mapping(self) -> Type[ServerProperties]:
+        return ServerProperties
+
+    @property
+    def query_runner(self) -> ServerRunner:
+        return ServerRunner(self.prop_mapping)
```
Comment (meoflynn) [inline lib/openstack_query/queries/server_query.py:40]: Could we add docstrings for these two methods?

File: lib/openstack_query/runners/user_runner.py [hunk 2]
```diff
@@ -25,14 +24,6 @@ class UserRunner(QueryRunner):
...
     DEFAULT_DOMAIN = UserDomains.STFC
 
-    @staticmethod
-    def _get_marker(obj: User) -> str:
-        """
-        This method returns the marker value for a User object, required for pagination
-        :param obj: An Server object to get the marker property for
-        """
-        return UserProperties.get_prop_mapping("id")(obj)
-
```
Comment (meoflynn) [inline lib/openstack_query/runners/user_runner.py:35]: Why has this method been removed?

**Review by meoflynn — CHANGES_REQUESTED** [review]

File: lib/openstack_query/query_base.py [hunk 3]
```diff
@@ -1,9 +1,12 @@
 from abc import ABC, abstractmethod
-from structs.query.query_client_side_handlers import QueryClientSideHandlers
+from typing import Type
+from typing import TypeVar
```
Comment (anish-mudaraddi) [inline lib/openstack_query/query_base.py:3]:
```suggestion
from typing import Type, TypeVar
```

File: lib/openstack_query/runners/query_runner.py [hunk 4]
```diff
@@ -155,7 +154,7 @@ def _run_paginated_query(
                 if i == self._LIMIT_FOR_PAGINATION - 1:
                     # restart the for loop with marker set
                     paginated_filters.update(
-                        {"marker": self._page_marker_prop_func(resource)}
+                        {"marker": self._prop_enum.get_prop_mapping(resource)}
```
[the remark this answers is not in the document]
Comment (anish-mudaraddi) [reply lib/openstack_query/runners/query_runner.py:157]: Plesae change the tests accordingly

File: lib/openstack_query/runners/user_runner.py (hunk 2 above)
Comment (anish-mudaraddi) [reply lib/openstack_query/runners/user_runner.py:35]: Looks to be a redundant function that I should have deleted

**Review by anish-mudaraddi — CHANGES_REQUESTED** [review]
Looks good - except for the issue with how pagination marker function is set. This should really have some acceptance testing done in a dev environment

File: lib/enums/query/props/prop_enum.py [hunk 5]
```diff
@@ -1,6 +1,10 @@
+from __future__ import annotations
```
Comment (anish-mudaraddi) [inline lib/enums/query/props/prop_enum.py:1]: Are you sure this works on Python 3.8? 
I believe I opted not to use this because of version dependencies when using python 3.6

Comment (DavidFair) [reply lib/enums/query/props/prop_enum.py:1]: We've dropped 3.6 with the upgrade, and I've just checked 3.7+ https://docs.python.org/3/library/__future__.html

File: lib/openstack_query/runners/query_runner.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (DavidFair) [reply lib/openstack_query/runners/query_runner.py:157]: Attempting to do this change results in the following:

```
                if i == self._LIMIT_FOR_PAGINATION - 1:
                    # restart the for loop with marker set
                    paginated_filters.update(
>                       {"marker": self._prop_enum.get_prop_mapping()(resource)}
                    )
E                   TypeError: QueryRunnerTests.setUp.<locals>.<lambda>() missing 1 required positional argument: 'mock_obj'

lib/openstack_query/runners/query_runner.py:157: TypeError
```

Since it looks like we need an object here, as we're now calling the lambda instead simply returning it?

**Comment by DavidFair** [comment]
Closing as stale
